<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UsuarioInscripcionBundleEntityAlumnoProxy extends \Usuario\InscripcionBundle\Entity\Alumno implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setDni($dni)
    {
        $this->__load();
        return parent::setDni($dni);
    }

    public function getDni()
    {
        $this->__load();
        return parent::getDni();
    }

    public function setLu($lu)
    {
        $this->__load();
        return parent::setLu($lu);
    }

    public function getLu()
    {
        $this->__load();
        return parent::getLu();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setApellido($apellido)
    {
        $this->__load();
        return parent::setApellido($apellido);
    }

    public function getApellido()
    {
        $this->__load();
        return parent::getApellido();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function addExpedientes(\Usuario\InscripcionBundle\Entity\Expediente $expediente)
    {
        $this->__load();
        return parent::addExpedientes($expediente);
    }

    public function getExpedientes()
    {
        $this->__load();
        return parent::getExpedientes();
    }

    public function addExpediente(\Usuario\InscripcionBundle\Entity\Expediente $expedientes)
    {
        $this->__load();
        return parent::addExpediente($expedientes);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'dni', 'lu', 'nombre', 'apellido', 'direccion', 'telefono', 'expedientes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}