parameters:
#    usuario_inscripcion.example.class: Usuario\InscripcionBundle\Example

services:
#    usuario_inscripcion.example:
#        class: %usuario_inscripcion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
